# Generated by Django 5.2 on 2025-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('networking', 'Networking'), ('meetup', 'Meetup'), ('expo', 'Expo'), ('trade_show', 'Trade Show'), ('product_launch', 'Product Launch'), ('fundraiser', 'Fundraiser'), ('social', 'Social'), ('party', 'Party'), ('performance', 'Performance'), ('exhibition', 'Exhibition'), ('retreat', 'Retreat'), ('panel', 'Panel'), ('class', 'Class'), ('festival', 'Festival'), ('meeting', 'Meeting'), ('sports', 'Sports'), ('volunteering', 'Volunteering'), ('holiday', 'Holiday')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('host_profile_name', models.CharField(max_length=30)),
                ('likes', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
