# Generated by Django 5.2 on 2025-04-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
    ]
