# Generated by Django 5.2 on 2025-04-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
